# Generated by Django 3.2.4 on 2021-06-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_conge_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.employee')),
            ],
        ),
    ]
